import React, { useState, useEffect } from 'react';
import { scanService } from '../../services/api';
import { FileText, Loader, AlertTriangle, CheckCircle, Download } from 'lucide-react';

const Reports = ({ refresh }) => {
    const [reports, setReports] = useState([]);
    const [loading, setLoading] = useState(true);
    const [selectedReport, setSelectedReport] = useState(null);

    useEffect(() => {
        fetchReports();
    }, [refresh]);

    const fetchReports = async () => {
        try {
            setLoading(true);
            const { data: scans } = await scanService.getScans();
            // Filter completed scans
            const completed = scans.filter(s => s.status === 'COMPLETED');
            setReports(completed);

            if (completed.length > 0 && !selectedReport) {
                // Fetch report for the latest one automatically
                fetchReportDetails(completed[0].id);
            }
        } catch (error) {
            console.error("Failed to fetch reports", error);
        } finally {
            setLoading(false);
        }
    };

    const fetchReportDetails = async (scanId) => {
        try {
            setLoading(true);
            const { data } = await scanService.getReport(scanId);
            setSelectedReport(data);
        } catch (error) {
            console.error("Failed to fetch report details", error);
        } finally {
            setLoading(false);
        }
    };

    const downloadPDF = async (scanId) => {
        try {
            const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000/api/v1';
            const url = `${API_URL}/reports/${scanId}/pdf`;

            // Open PDF in new window/download
            window.open(url, '_blank');
        } catch (error) {
            console.error("Failed to download PDF", error);
        }
    };

    if (loading && !reports.length) {
        return (
            <div className="flex justify-center items-center h-64 text-cyber-accent">
                <Loader className="h-10 w-10 animate-spin" />
            </div>
        );
    }

    if (reports.length === 0) {
        return (
            <div className="text-center py-12 bg-cyber-light rounded-xl border border-gray-700">
                <FileText className="h-16 w-16 text-gray-600 mx-auto mb-4" />
                <h3 className="text-xl font-bold text-white">No Reports Available</h3>
                <p className="text-gray-400">Complete a scan to generate a security report.</p>
            </div>
        );
    }

    return (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 h-[calc(100vh-200px)]">
            {/* List */}
            <div className="bg-cyber-light rounded-xl border border-gray-700 overflow-hidden flex flex-col">
                <div className="p-4 border-b border-gray-700 bg-gray-900/50">
                    <h3 className="font-bold text-white flex items-center gap-2">
                        <FileText className="h-4 w-4 text-cyber-accent" />
                        Available Reports
                    </h3>
                </div>
                <div className="overflow-y-auto flex-1 p-2 space-y-2">
                    {reports.map((scan) => (
                        <div
                            key={scan.id}
                            onClick={() => fetchReportDetails(scan.id)}
                            className={`p-3 rounded-lg cursor-pointer transition-colors border ${selectedReport?.scan_id === scan.id ? 'bg-cyber-accent/10 border-cyber-accent text-white' : 'bg-gray-800/50 border-transparent text-gray-400 hover:bg-gray-800'}`}
                        >
                            <div className="flex justify-between items-center mb-1">
                                <span className="font-bold text-sm">Scan #{scan.id}</span>
                                <span className="text-xs font-mono">{new Date(scan.completed_at).toLocaleDateString()}</span>
                            </div>
                            <div className="text-xs truncate">{scan.target}</div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Viewer */}
            <div className="md:col-span-2 bg-cyber-light rounded-xl border border-gray-700 overflow-hidden flex flex-col">
                {selectedReport ? (
                    <>
                        <div className="p-6 border-b border-gray-700 bg-gray-900/50 flex justify-between items-center">
                            <div>
                                <h2 className="text-xl font-bold text-white">Executive Summary</h2>
                                <p className="text-gray-400 text-sm">Generated by AI Security Advisor</p>
                            </div>
                            <button
                                onClick={() => downloadPDF(selectedReport.scan_id)}
                                className="flex items-center gap-2 px-3 py-1.5 bg-cyber-accent text-gray-900 rounded font-bold text-sm hover:bg-white transition-colors"
                            >
                                <Download className="h-4 w-4" />
                                Export PDF
                            </button>
                        </div>
                        <div className="p-8 overflow-y-auto prose prose-invert max-w-none">
                            <div className="whitespace-pre-wrap font-sans text-gray-300">
                                {selectedReport.ai_analysis || "No content available."}
                            </div>
                        </div>
                    </>
                ) : (
                    <div className="flex-1 flex flex-col justify-center items-center text-gray-500">
                        <Loader className="h-12 w-12 animate-spin mb-4" />
                        <p>Loading report details...</p>
                    </div>
                )}
            </div>
        </div>
    );
};

export default Reports;
