"""add_risk_fields

Revision ID: 42961c8452a4
Revises: 8192bff0e1e0
Create Date: 2026-02-12 23:51:17.393110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42961c8452a4'
down_revision: Union[str, None] = '8192bff0e1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_assets', sa.Column('criticality', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='asset_criticality_enum'), nullable=True))
    op.add_column('network_assets', sa.Column('risk_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network_assets', 'risk_score')
    op.drop_column('network_assets', 'criticality')
    # ### end Alembic commands ###
