"""add openvas fields to vulnerabilities

Revision ID: 8192bff0e1e0
Revises: 97af5de1cc55
Create Date: 2026-02-13 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8192bff0e1e0'
down_revision: Union[str, None] = '97af5de1cc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('vulnerabilities', sa.Column('simplified_description', sa.Text(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('remediation_steps', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'remediation_steps')
    op.drop_column('vulnerabilities', 'simplified_description')
    op.drop_column('vulnerabilities', 'title')
    # ### end Alembic commands ###
