"""Add mac_vendor fields and asset_services table

Revision ID: 97af5de1cc55
Revises: 
Create Date: 2026-01-26 20:17:27.340754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97af5de1cc55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_assets', sa.Column('mac_vendor', sa.String(), nullable=True))
    op.add_column('scan_assets', sa.Column('os_family', sa.String(), nullable=True))
    op.add_column('scan_assets', sa.Column('os_accuracy', sa.Integer(), nullable=True))
    op.add_column('scan_assets', sa.Column('uptime', sa.String(), nullable=True))
    op.add_column('scan_assets', sa.Column('first_seen', sa.DateTime(), nullable=True))
    op.add_column('scan_assets', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_assets', 'last_seen')
    op.drop_column('scan_assets', 'first_seen')
    op.drop_column('scan_assets', 'uptime')
    op.drop_column('scan_assets', 'os_accuracy')
    op.drop_column('scan_assets', 'os_family')
    op.drop_column('scan_assets', 'mac_vendor')
    # ### end Alembic commands ###
